a = input()
b = int(input())
c = int(input())
d = int(input())
print("Чек")
print(a, "-", str(c) + "кг", "-", str(b) + "руб/кг")
print("Итого:", str(b * c) + "руб")
print("Внесено:", str(d) + "руб")
print("Сдача:", str(d - (b * c)) + "руб")